
payload:
  - DOMAIN-SUFFIX,cn2gias.uk 
  - DOMAIN-KEYWORD,magpie
  - DOMAIN-SUFFIX,embymv.link
  - DOMAIN-SUFFIX,pdatv.cc
  - DOMAIN-SUFFIX,cn2gias.uk
  - DOMAIN-SUFFIX,jmsooo.com
  - DOMAIN-SUFFIX,023168.xyz
  - DOMAIN-SUFFIX,223789.xyz
  - DOMAIN-SUFFIX,cc.ccemby.tk
  - DOMAIN-SUFFIX,line.emby.men
  - DOMAIN-SUFFIX,mius.uk
  - DOMAIN-SUFFIX,emby.flowercloud
  - DOMAIN-SUFFIX,emby.immtel.com
  - DOMAIN-SUFFIX,ju.dog
  - DOMAIN-SUFFIX,charontv.com
  - DOMAIN-SUFFIX,push-kr.cfprefer3.xyz
  - DOMAIN-SUFFIX,mjjemby.org
  - DOMAIN-SUFFIX,emby.maying.club
  - DOMAIN-SUFFIX,ntrrr.am.sb
  - DOMAIN-SUFFIX,emby.nexitally.com
  - DOMAIN-SUFFIX,direct.nebula-emby.com
  - DOMAIN-SUFFIX,odysseyplus.site
  - DOMAIN-SUFFIX,zox.show
  - DOMAIN-SUFFIX,nezhasu.com
  - DOMAIN-SUFFIX,roboemby.de
  - DOMAIN-SUFFIX,616626.xyz
  - DOMAIN-SUFFIX,niceduck.lol
  - DOMAIN-SUFFIX,kevinchen.vip
  - DOMAIN-SUFFIX,5203166.xyz
  - DOMAIN-SUFFIX,alphatvapp.top
  - DOMAIN-SUFFIX,204cloud.com
  - DOMAIN-SUFFIX,misty.cx
  - DOMAIN-SUFFIX,313445.xyz
  - DOMAIN-SUFFIX,synn.cc
  - DOMAIN-SUFFIX,127255.best
  - DOMAIN-SUFFIX,127066.xyz
  - DOMAIN-SUFFIX,raisemby.com
  - DOMAIN-SUFFIX,oceancloud.asia
  - DOMAIN-SUFFIX,embyplus.org
  - DOMAIN-SUFFIX,nijigem.by
  - DOMAIN-SUFFIX,cdn.bgp.yt
  - DOMAIN-SUFFIX,bangumi.ca
  - DOMAIN-SUFFIX,aliz.work
  - DOMAIN-SUFFIX,cherry-pornemby.top
  - DOMAIN-SUFFIX,dhyy.eu.org
  - DOMAIN-SUFFIX,xxxh.de
  - DOMAIN-SUFFIX,mefun.org
  - DOMAIN-SUFFIX,mobaiemby.site
  - DOMAIN-SUFFIX,ii00.cc
  - DOMAIN-SUFFIX,guguemby.site
  - DOMAIN-SUFFIX,sexemby.com
  - DOMAIN-SUFFIX,pilipiliultra.com
  - DOMAIN-SUFFIX,pilipiliultra.com
  - DOMAIN-SUFFIX,pilipili.me
  - DOMAIN-SUFFIX,pili.im
  - DOMAIN-SUFFIX,wenjian.de
  - DOMAIN-SUFFIX,tanhuatv.site
  - DOMAIN-SUFFIX,younoyes.com
  - IP-CIDR,120.226.149.35/32,no-resolve
  - IP-CIDR,116.163.28.190/32,no-resolve
