payload:
  - DOMAIN,wgtv.ii00.cc
  - DOMAIN,wptv.ii00.cc
  - DOMAIN,music.mefun.vip
  - DOMAIN-SUFFIX,src-emby.cn2gias.uk
  - DOMAIN-SUFFIX,bili.bili.rip
  - DOMAIN-SUFFIX,ntrrr.am.sb
  - DOMAIN-SUFFIX,stream.synn.cc
  - DOMAIN-SUFFIX,stream.ntrrr.top
  - DOMAIN-SUFFIX,stream-zz.synn.cc
  - DOMAIN-SUFFIX,789.123456.al
  - DOMAIN-SUFFIX,emby.mius.uk
  - DOMAIN-SUFFIX,pub1.emby.wtf
  - DOMAIN-SUFFIX,pub2.emby.wtf
  - DOMAIN-SUFFIX,pub3.emby.wtf
  - DOMAIN-SUFFIX,misakaf.org
  - DOMAIN-SUFFIX,stream1.misakaf.org
  - DOMAIN-SUFFIX,stream2.misakaf.org
  - DOMAIN-SUFFIX,stream3.misakaf.org
  - DOMAIN-SUFFIX,e.niceduck.me
  - DOMAIN-SUFFIX,embyvip.misakaf.org
  - DOMAIN-SUFFIX,push-kr.misakaf.org
  - DOMAIN-SUFFIX,direct.lyrebirdemby.com
  - DOMAIN-SUFFIX,cdn.lyrebirdemby.com
  - DOMAIN-SUFFIX,cf.niceduck.lol
  - DOMAIN-SUFFIX,vi.niceduck.lol
  - DOMAIN-SUFFIX,line.xmsl.org
  - DOMAIN-SUFFIX,public.emby.ws
  - DOMAIN-SUFFIX,embyplus.org
  - DOMAIN-SUFFIX,cdn.bili.rip
  - DOMAIN-SUFFIX,pub1cf.emby.wtf
  - DOMAIN-SUFFIX,pub2cf.emby.wtf
  - DOMAIN-SUFFIX,pub3cf.emby.wtf
  - DOMAIN-SUFFIX,notnetflix.cos.cat
  - DOMAIN-SUFFIX,emby.pilipiliultra.top
  - DOMAIN-SUFFIX,jms.niceduck.lol
  - DOMAIN-SUFFIX,1111cuct.niceduck.lol
  - DOMAIN-SUFFIX,gd.9521732.xyz
  - DOMAIN-SUFFIX,chirsemby.top
  - DOMAIN-SUFFIX,emby-us-v4.mius.uk
  - DOMAIN-SUFFIX,emby-fr-v6.mius.uk
  - DOMAIN-SUFFIX,hxd.as174.com
  - DOMAIN-SUFFIX,cf.bili.rip
  - DOMAIN-SUFFIX,mix.1steam.one
  - DOMAIN-SUFFIX,rd.happyav.eu.org
  - DOMAIN-SUFFIX,new.happyav.eu.org
  - DOMAIN-SUFFIX,nanflix.net
  - DOMAIN-SUFFIX,embymv.link
  - IP-CIDR,108.181.0.21/32,no-resolve
  - IP-CIDR,168.138.45.100/32,no-resolve
  - DOMAIN,emby.my
